name: deploy-client-package

on:
  push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Push to client package repository
      id: push_directory
      uses: cpina/github-action-push-to-another-repository@target-branch
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-directory: 'client-package'
        destination-github-username: 'acm-ndsu'
        destination-repository-name: 'Byte-le-2026-Client-Package'
        user-email: noah.magcalas@gmail.com
        commit-message: See ORIGIN_COMMIT from $GITHUB_REF
        target-branch: main
    - name: Test get variable exported by push-to-another-repository
      run: echo $DESTINATION_CLONED_DIRECTORY
